"""Single-checkpoint T2A (TTS) inference.

A pared-down counterpart to ``infer/audio/run_eval.py``: instead of sweeping
``(cfg, ckpt)``, this script generates wavs for **one** checkpoint at **one**
guidance scale. Inputs are either a list of ``--prompt`` strings or a
``--prompts-file`` (``.jsonl`` / ``.metalst``).

VAE selection rule (per user request, deliberately different from ``run_eval``):

* By default, the audio VAE is loaded from the YAML's
  ``audio_vae.model_path``. The checkpoint's ``metadata.json`` is **not**
  consulted for ``vae_model_name_or_path`` here (use ``run_eval.py`` if you
  need that behaviour).
* If ``--vae`` is supplied, it overrides ``audio_vae.model_path``.

Launch with ``accelerate launch`` to shard prompts across ranks (each prompt
is generated by exactly one rank, transcriptions are gathered to the main
rank). Running ``python infer/audio/run_tts.py`` directly works as a single-
process smoke test.

Outputs (under ``--output-dir``)::

    <output_dir>/
    ├── prompts.jsonl              # only when --prompt was used
    ├── meta.jsonl                 # one row per generated wav
    ├── <type-slug>/<index>.wav    # the generated audio
    ├── wer.jsonl                  # only when WER is enabled
    ├── wer_summary.json           # only when WER is enabled
    └── run_manifest.json          # full CLI / resolved-config snapshot
"""
from __future__ import annotations

import argparse
import gc
import json
import sys
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from omnivae_generation.trainer.runtime_env import ensure_hf_home  # noqa: E402

ensure_hf_home()

import torch  # noqa: E402
from accelerate import Accelerator  # noqa: E402
from accelerate.utils import gather_object  # noqa: E402
from diffusers import FlowMatchEulerDiscreteScheduler, ZImageTransformer2DModel  # noqa: E402
from transformers import AutoModel, AutoTokenizer  # noqa: E402

from omnivae_generation.trainer.audio_validation import (  # noqa: E402
    _audio_vae_hop_length,
    _generate_one_set,
    _load_asr_if_enabled,
    _persist_set_outputs,
    _slug,
)
from omnivae_generation.trainer.audio_wer import score_records, transcribe_records  # noqa: E402
from omnivae_generation.trainer.config import load_config  # noqa: E402
from omnivae_generation.trainer.data import maybe_format_chat_prompt  # noqa: E402
from omnivae_generation.trainer.modeling import (  # noqa: E402
    configure_transformer_prediction_target,
    configure_transformer_timestep_usage,
    encode_prompts,
    load_audio_vae,
    resolve_dtype,
)
from omnivae_generation.trainer.runtime_patches import (  # noqa: E402
    patch_diffusers_zimage_forward_block_stacks,
    patch_diffusers_zimage_real_rope,
    patch_transformers_qwen3_5_disable_fast_path,
)
from omnivae_generation.trainer.utils import ensure_dir  # noqa: E402
from omnivae_generation.trainer.forward_transformer import build_forward_transformer  # noqa: E402

from infer.audio.run_eval import _make_duration_estimator, _trim_wave_for_asr  # noqa: E402


# ---------------------------------------------------------------------------
# argparse
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run T2A (text-to-audio / TTS) inference for ONE checkpoint at ONE "
            "guidance scale. VAE defaults to the YAML's audio_vae.model_path; "
            "pass --vae to override."
        ),
    )
    parser.add_argument(
        "--config",
        required=True,
        help="Training YAML used to build text encoder / VAE / scheduler / dataset rates.",
    )
    parser.add_argument(
        "--checkpoint",
        required=True,
        help=(
            "Path to a single checkpoint dir (must contain transformer/, and "
            "optionally scheduler/ and metadata.json). The transformer config "
            "and weights here drive the run."
        ),
    )
    parser.add_argument(
        "--vae",
        type=str,
        default=None,
        help=(
            "Optional override for the audio VAE .pth path. When omitted, "
            "audio_vae.model_path from the YAML is used; the checkpoint's "
            "metadata.json is intentionally NOT consulted here."
        ),
    )
    # Prompt sources: pick exactly one of (--prompt / --prompts-file).
    parser.add_argument(
        "--prompt",
        action="append",
        default=[],
        help=(
            "Inline prompt text. Repeatable; each invocation adds one prompt. "
            "Mutually exclusive with --prompts-file."
        ),
    )
    parser.add_argument(
        "--prompts-file",
        type=str,
        default=None,
        help=(
            "Path to a prompts file (jsonl or metalst). Schema follows "
            "omnivae_generation.trainer.audio_wer.load_prompt_set: jsonl rows must contain at "
            "least the text field (default 'text')."
        ),
    )
    parser.add_argument(
        "--prompts-format",
        choices=["jsonl", "metalst"],
        default=None,
        help="Override format detection for --prompts-file (default: from extension).",
    )
    parser.add_argument(
        "--text-field",
        type=str,
        default="text",
        help="JSONL field carrying the prompt text (default: text).",
    )
    parser.add_argument(
        "--type-field",
        type=str,
        default="type",
        help="JSONL field carrying the type/category label (default: type).",
    )
    parser.add_argument(
        "--index-field",
        type=str,
        default="index",
        help="JSONL field carrying the per-row index (default: index).",
    )
    parser.add_argument(
        "--num-prompts",
        type=int,
        default=None,
        help="Cap the number of prompts loaded from --prompts-file.",
    )

    parser.add_argument(
        "--cfg",
        type=float,
        default=None,
        help=(
            "Guidance scale (codebase convention: pred = pos + s*(pos-neg)). "
            "Default: validation.guidance_scale from the YAML, or 3.0 if absent."
        ),
    )
    parser.add_argument(
        "--num-inference-steps",
        type=int,
        default=None,
        help="Override validation.num_inference_steps.",
    )
    parser.add_argument(
        "--duration-seconds",
        type=float,
        default=None,
        help=(
            "Latent length in seconds (default: validation.duration_seconds, "
            "or 30s if absent). Also acts as the upper clamp for the per-prompt "
            "target duration when --prompt-duration-strategy is 'auto' or 'f5'."
        ),
    )

    parser.add_argument(
        "--prompt-duration-strategy",
        choices=["auto", "fixed", "f5"],
        default="f5",
        help=(
            "How to fill the 'duration: X.Xs' suffix in the prompt. Mirrors "
            "infer/audio/run_eval.py."
        ),
    )
    parser.add_argument("--auto-duration-words-per-second", type=float, default=3.0)
    parser.add_argument("--auto-duration-margin-seconds", type=float, default=0.5)
    parser.add_argument("--auto-duration-min-seconds", type=float, default=3.0)
    parser.add_argument(
        "--auto-duration-max-seconds",
        type=float,
        default=None,
        help="Default (None) = --duration-seconds.",
    )
    parser.add_argument("--f5-bytes-per-second", type=float, default=17.0)
    parser.add_argument("--f5-local-speed", type=float, default=1.0)
    parser.add_argument("--f5-short-text-threshold-bytes", type=int, default=10)
    parser.add_argument("--f5-short-text-local-speed", type=float, default=0.3)
    parser.add_argument("--f5-margin-seconds", type=float, default=0.0)

    parser.add_argument(
        "--asr-trim-to-prompt-duration",
        dest="asr_trim_to_prompt_duration",
        action="store_true",
        default=True,
    )
    parser.add_argument(
        "--no-asr-trim-to-prompt-duration",
        dest="asr_trim_to_prompt_duration",
        action="store_false",
    )
    parser.add_argument("--asr-trim-padding-seconds", type=float, default=0.5)
    parser.add_argument(
        "--trim-output-wav",
        action="store_true",
        help=(
            "Also truncate the wav saved to disk to (target_duration + "
            "asr-trim-padding). Default off."
        ),
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Base seed (default: train.seed from config). None -> random per call.",
    )
    parser.add_argument(
        "--seed-offset",
        type=int,
        default=0,
        help="Added to (base_seed + global_idx) for each prompt.",
    )

    parser.add_argument(
        "--output-dir",
        required=True,
        help="Where to write wavs / meta.jsonl / run_manifest.json.",
    )
    parser.add_argument(
        "--set-name",
        type=str,
        default="tts",
        help=(
            "Name reported in meta.jsonl / wer_summary.json. Inline prompts "
            "default to 'tts'; for a --prompts-file you may want the file stem."
        ),
    )

    # WER (optional). Default follows the YAML; --enable-wer / --disable-wer
    # force the behaviour regardless.
    parser.add_argument(
        "--enable-wer",
        dest="enable_wer",
        action="store_true",
        default=None,
    )
    parser.add_argument(
        "--disable-wer",
        dest="enable_wer",
        action="store_false",
    )
    parser.add_argument(
        "--wer-normalization",
        choices=["simple", "seedtts"],
        default="simple",
        help=(
            "Normalization mode passed to omnivae_generation.trainer.audio_wer.score_records. "
            "These are the only two modes upstream supports: 'simple' strips "
            "all string.punctuation incl. apostrophe; 'seedtts' keeps the "
            "apostrophe and additionally strips zhon.hanzi punctuation."
        ),
    )

    parser.add_argument(
        "--task-kind",
        choices=["tts", "tta", "auto"],
        default="auto",
        help=(
            "Task pool to draw the instruction-style prefix template from. "
            "'auto' defers to omnivae_generation.trainer.audio_task_prefix.resolve_task_kind, "
            "which falls back to TTS for run_tts.py's metalst-style entries."
        ),
    )
    parser.add_argument(
        "--no-task-prefix",
        dest="task_prefix_enabled",
        action="store_false",
        default=True,
        help=(
            "Disable the instruction-style task prefix wrap (ablation). "
            "Default: enabled, matching how the model was trained."
        ),
    )

    args = parser.parse_args()

    if not args.prompt and not args.prompts_file:
        parser.error("Provide at least one of --prompt or --prompts-file.")
    if args.prompt and args.prompts_file:
        parser.error("--prompt and --prompts-file are mutually exclusive.")

    return args


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _apply_runtime_patches(config: dict) -> None:
    patch_diffusers_zimage_real_rope()
    patch_diffusers_zimage_forward_block_stacks()
    if config["text_encoder"].get("disable_qwen3_5_fast_path", False):
        patch_transformers_qwen3_5_disable_fast_path()


def _build_text_encoder(config: dict, device: torch.device):
    """Same shape as omnivae_generation.trainer.modeling.load_text_components, minus the compile
    path. Reused unchanged across the whole run.
    """
    text_cfg = config["text_encoder"]
    text_dtype = resolve_dtype(text_cfg.get("torch_dtype"), fallback=torch.bfloat16)

    tokenizer = AutoTokenizer.from_pretrained(
        text_cfg["model_name_or_path"],
        trust_remote_code=text_cfg.get("trust_remote_code", False),
        local_files_only=text_cfg.get("local_files_only", False),
    )
    if tokenizer.pad_token is None and tokenizer.eos_token is not None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model_kwargs: dict[str, Any] = {
        "trust_remote_code": text_cfg.get("trust_remote_code", False),
        "torch_dtype": text_dtype,
        "low_cpu_mem_usage": True,
        "local_files_only": text_cfg.get("local_files_only", False),
    }
    attn_implementation = text_cfg.get("attn_implementation")
    if attn_implementation:
        model_kwargs["attn_implementation"] = attn_implementation
    text_encoder = AutoModel.from_pretrained(text_cfg["model_name_or_path"], **model_kwargs)
    text_encoder.eval()
    text_encoder.to(device)
    return tokenizer, text_encoder, text_dtype


def _build_audio_vae(config: dict, vae_override: str | None, device: torch.device):
    """Resolve the VAE path per the user-facing rule:
    1. Use --vae if given.
    2. Otherwise use config["audio_vae"]["model_path"] (or "model_name_or_path").
    The checkpoint's metadata.json is *not* consulted here (use run_eval.py
    if you need that behaviour).
    """
    audio_cfg = dict(config.get("audio_vae") or {})
    yaml_path = audio_cfg.get("model_path") or audio_cfg.get("model_name_or_path")

    if vae_override:
        chosen = str(Path(vae_override).expanduser())
        source = "cli"
    elif yaml_path:
        chosen = str(Path(str(yaml_path)).expanduser())
        source = "yaml"
    else:
        raise SystemExit(
            "No audio VAE configured: pass --vae or set audio_vae.model_path "
            "in the YAML."
        )

    audio_cfg["model_path"] = chosen
    vae_model = load_audio_vae(audio_cfg)
    vae_model.eval()
    vae_model.to(device)
    return vae_model, audio_cfg, chosen, source


def _load_transformer(ckpt_dir: Path, *, config: dict, device: torch.device, dtype: torch.dtype):
    """Load transformer + scheduler from a single checkpoint directory.

    Mirrors infer.audio.run_eval._load_transformer_for_ckpt; the early
    "config.json missing" guard is kept because mid-rotation snapshots can
    disappear under us with no warning.
    """
    transformer_dir = ckpt_dir / "transformer"
    if not (transformer_dir / "config.json").is_file():
        raise FileNotFoundError(
            f"Checkpoint at {ckpt_dir} is missing {transformer_dir / 'config.json'}"
        )
    transformer = ZImageTransformer2DModel.from_pretrained(
        str(transformer_dir),
        torch_dtype=dtype,
    )
    transformer.eval()
    configure_transformer_timestep_usage(transformer, config["transformer"].get("use_timestep", True))
    configure_transformer_prediction_target(transformer, config["transformer"].get("predict_target", "v"))
    if hasattr(transformer, "set_forward_compilation"):
        transformer.set_forward_compilation(False)
    transformer.to(device)
    if hasattr(transformer, "materialize_rope_cache"):
        transformer.materialize_rope_cache(device)

    scheduler_dir = ckpt_dir / "scheduler"
    if scheduler_dir.is_dir():
        scheduler = FlowMatchEulerDiscreteScheduler.from_pretrained(str(scheduler_dir))
    else:
        sched_cfg = config["scheduler"]
        scheduler = FlowMatchEulerDiscreteScheduler.from_pretrained(
            sched_cfg["model_name_or_path"],
            subfolder=sched_cfg.get("subfolder", "scheduler"),
            local_files_only=sched_cfg.get("local_files_only", False),
        )
    return transformer, scheduler


def _resolve_explicit_task_kind(args: argparse.Namespace) -> str | None:
    """Translate ``--task-kind`` into a value suitable for set_cfg.

    ``auto`` -> ``None`` (let resolve_task_kind decide per-entry).
    ``tts`` / ``tta`` -> stored on set_cfg so resolve_task_kind picks it up.
    """
    raw = str(getattr(args, "task_kind", "auto") or "auto").strip().lower()
    if raw in ("tts", "tta"):
        return raw
    return None


def _build_set_cfg_from_inline_prompts(
    prompts: list[str],
    *,
    output_dir: Path,
    set_name: str,
    accelerator: Accelerator,
    task_kind: str | None,
) -> dict:
    """Materialize ``--prompt`` strings to a tiny prompts.jsonl on the main
    rank, then return a set_cfg pointing at it. We go through
    ``_generate_one_set`` rather than re-deriving the per-prompt loop so the
    behaviour stays bit-identical to training-time validation.
    """
    prompts_path = output_dir / "prompts.jsonl"
    if accelerator.is_main_process:
        ensure_dir(output_dir)
        with prompts_path.open("w", encoding="utf-8") as fh:
            for i, text in enumerate(prompts):
                fh.write(
                    json.dumps(
                        {"index": i, "type": "all", "text": text},
                        ensure_ascii=False,
                    )
                    + "\n"
                )
    accelerator.wait_for_everyone()
    return {
        "name": set_name,
        "path": str(prompts_path),
        "format": "jsonl",
        "text_field": "text",
        "type_field": "type",
        "index_field": "index",
        "wer_normalization": "simple",
        "task_kind": task_kind,
    }


def _build_set_cfg_from_file(args: argparse.Namespace, task_kind: str | None) -> dict:
    p = Path(args.prompts_file).expanduser()
    if not p.is_file():
        raise SystemExit(f"--prompts-file does not exist: {p}")
    fmt = args.prompts_format
    if not fmt:
        ext = p.suffix.lower().lstrip(".")
        if ext in {"jsonl", "metalst"}:
            fmt = ext
        else:
            raise SystemExit(
                f"Could not auto-detect format for --prompts-file={p}; pass "
                f"--prompts-format=jsonl or --prompts-format=metalst."
            )
    return {
        "name": args.set_name,
        "path": str(p),
        "format": fmt,
        "text_field": args.text_field,
        "type_field": args.type_field,
        "index_field": args.index_field,
        "wer_normalization": args.wer_normalization,
        "num_prompts": args.num_prompts,
        "task_kind": task_kind,
    }


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


@torch.no_grad()
def main() -> int:
    args = parse_args()

    config = load_config(args.config)
    _apply_runtime_patches(config)

    accelerator = Accelerator()
    device = accelerator.device

    output_dir = Path(args.output_dir).expanduser().resolve()

    # Resolve runtime knobs from the YAML, then apply CLI overrides.
    val_cfg = dict(config.get("validation") or {})
    duration_seconds = float(
        args.duration_seconds
        if args.duration_seconds is not None
        else val_cfg.get("duration_seconds", 30.0)
    )
    num_inference_steps = int(
        args.num_inference_steps
        if args.num_inference_steps is not None
        else val_cfg.get("num_inference_steps", 25)
    )
    cfg_value = float(
        args.cfg if args.cfg is not None else val_cfg.get("guidance_scale", 3.0)
    )
    cfg_normalization = bool(val_cfg.get("cfg_normalization", False))

    base_seed = int(args.seed) if args.seed is not None else config["train"].get("seed")
    seed_offset = int(args.seed_offset)

    dataset_cfg = config.get("dataset", {})
    sample_rate = int(dataset_cfg.get("sample_rate", 48000))
    duration_precision = int(dataset_cfg.get("duration_precision", 1))
    append_duration_suffix = bool(dataset_cfg.get("append_duration_suffix", True))

    # Build the prompt set descriptor (file path or inline-materialized jsonl).
    explicit_task_kind = _resolve_explicit_task_kind(args)
    if args.prompt:
        set_cfg = _build_set_cfg_from_inline_prompts(
            args.prompt,
            output_dir=output_dir,
            set_name=args.set_name,
            accelerator=accelerator,
            task_kind=explicit_task_kind,
        )
    else:
        set_cfg = _build_set_cfg_from_file(args, task_kind=explicit_task_kind)
    if args.num_prompts is not None:
        set_cfg["num_prompts"] = int(args.num_prompts)

    auto_max_seconds = (
        float(args.auto_duration_max_seconds)
        if args.auto_duration_max_seconds is not None
        else float(duration_seconds)
    )
    duration_estimator = _make_duration_estimator(
        strategy=str(args.prompt_duration_strategy),
        fixed_duration=duration_seconds,
        words_per_second=args.auto_duration_words_per_second,
        margin_seconds=args.auto_duration_margin_seconds,
        min_seconds=args.auto_duration_min_seconds,
        max_seconds=auto_max_seconds,
        bytes_per_second=args.f5_bytes_per_second,
        f5_local_speed=args.f5_local_speed,
        f5_short_text_threshold_bytes=args.f5_short_text_threshold_bytes,
        f5_short_text_local_speed=args.f5_short_text_local_speed,
        f5_margin_seconds=args.f5_margin_seconds,
    )

    text_dtype = resolve_dtype(config["text_encoder"].get("torch_dtype"), fallback=torch.bfloat16)
    transformer_dtype = text_dtype if device.type == "cuda" else torch.float32

    if accelerator.is_main_process:
        print("Loading text encoder + tokenizer ...", flush=True)
    tokenizer, text_encoder_model, _ = _build_text_encoder(config, device)

    if accelerator.is_main_process:
        print("Loading audio VAE ...", flush=True)
    vae_model, resolved_audio_cfg, vae_path, vae_source = _build_audio_vae(
        config, args.vae, device
    )
    hop_length = _audio_vae_hop_length(vae_model, resolved_audio_cfg)
    t_latent = max(1, int(round(duration_seconds * sample_rate / hop_length)))

    ckpt_dir = Path(args.checkpoint).expanduser().resolve()
    if accelerator.is_main_process:
        print(f"Loading transformer from {ckpt_dir} ...", flush=True)
    transformer_model, scheduler = _load_transformer(
        ckpt_dir,
        config=config,
        device=device,
        dtype=transformer_dtype,
    )
    forward_transformer = build_forward_transformer(
        transformer_model,
        transformer_model,
        train_patch_size=int(config["transformer"]["all_patch_size"][0]),
        train_f_patch_size=int(config["transformer"]["all_f_patch_size"][0]),
    )

    max_seq_len = int(config["text_encoder"]["max_sequence_length"])
    cache_enabled = bool(config["text_encoder"].get("cache_enabled", False))
    in_channels = int(config["transformer"]["in_channels"])

    empty_prompt_text = maybe_format_chat_prompt("", tokenizer)
    negative_prompt_embeds = encode_prompts(
        [empty_prompt_text],
        tokenizer,
        text_encoder_model,
        device,
        max_seq_len,
        cache_enabled=cache_enabled,
    )

    # WER (optional). If --enable-wer / --disable-wer is set, override the YAML
    # toggle while preserving its model_path / target_sample_rate / ...
    if args.enable_wer is not None:
        wer_block = dict(val_cfg.get("wer") or {})
        wer_block["enabled"] = bool(args.enable_wer)
        val_cfg_for_asr = dict(val_cfg)
        val_cfg_for_asr["wer"] = wer_block
    else:
        val_cfg_for_asr = val_cfg
    asr = _load_asr_if_enabled(val_cfg_for_asr, accelerator)

    # Persist the run manifest before generation kicks off so we capture intent
    # even if the run dies mid-loop.
    if accelerator.is_main_process:
        ensure_dir(output_dir)
        ckpt_meta = {}
        meta_path_in_ckpt = ckpt_dir / "metadata.json"
        if meta_path_in_ckpt.is_file():
            try:
                ckpt_meta = json.loads(meta_path_in_ckpt.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                ckpt_meta = {}
        manifest = {
            "config": str(Path(args.config).resolve()),
            "checkpoint": str(ckpt_dir),
            "checkpoint_metadata": ckpt_meta,
            "vae_path": vae_path,
            "vae_source": vae_source,  # "cli" or "yaml"
            "output_dir": str(output_dir),
            "cfg": cfg_value,
            "cfg_normalization": cfg_normalization,
            "num_inference_steps": num_inference_steps,
            "duration_seconds": duration_seconds,
            "t_latent": t_latent,
            "hop_length": hop_length,
            "sample_rate": sample_rate,
            "duration_precision": duration_precision,
            "append_duration_suffix": append_duration_suffix,
            "base_seed": base_seed,
            "seed_offset": seed_offset,
            "set_cfg": set_cfg,
            "prompt_duration_strategy": str(args.prompt_duration_strategy),
            "task_prefix_enabled": bool(args.task_prefix_enabled),
            "task_kind": explicit_task_kind,
            "world_size": int(accelerator.num_processes),
            "wer": {
                "enabled": asr is not None,
                "normalization": str(args.wer_normalization),
            },
        }
        (output_dir / "run_manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        print("TTS run:")
        print(f"  ckpt: {ckpt_dir}")
        print(f"  vae:  {vae_path}  (source={vae_source})")
        print(f"  cfg:  {cfg_value}  steps={num_inference_steps}  duration={duration_seconds}s")
        print(f"  set:  name={set_cfg['name']} path={set_cfg['path']}")
        print(f"  out:  {output_dir}")

    try:
        local_results = _generate_one_set(
            accelerator=accelerator,
            config=config,
            set_cfg=set_cfg,
            transformer_model=transformer_model,
            text_encoder_model=text_encoder_model,
            vae_model=vae_model,
            scheduler=scheduler,
            forward_transformer=forward_transformer,
            negative_prompt_embeds=negative_prompt_embeds,
            tokenizer=tokenizer,
            base_seed=base_seed,
            step=0,
            seed_offset=seed_offset,
            duration_seconds=duration_seconds,
            duration_precision=duration_precision,
            append_duration_suffix=append_duration_suffix,
            num_inference_steps=num_inference_steps,
            guidance_scale=cfg_value,
            cfg_normalization=cfg_normalization,
            in_channels=in_channels,
            t_latent=t_latent,
            max_seq_len=max_seq_len,
            cache_enabled=cache_enabled,
            duration_seconds_for_text=duration_estimator,
            task_prefix_enabled=bool(args.task_prefix_enabled),
            sample_rate=sample_rate,
            hop_length=hop_length,
            progress_desc=("tts" if accelerator.is_main_process else None),
        )

        # Optionally trim each wave to (target_duration + padding) before ASR
        # so post-utterance hallucinations don't pollute WER. Disk wavs follow
        # the same semantics as run_eval (controlled by --trim-output-wav).
        saved_full_waves = None
        if asr is not None and args.asr_trim_to_prompt_duration and local_results:
            saved_full_waves = _trim_wave_for_asr(
                local_results,
                sample_rate=sample_rate,
                padding_seconds=float(args.asr_trim_padding_seconds),
                persist_truncation=bool(args.trim_output_wav),
            )

        if asr is not None and local_results:
            transcribe_records(
                local_results,
                asr=asr,
                sample_rate=sample_rate,
                progress_desc="asr" if accelerator.is_main_process else None,
            )

        if saved_full_waves:
            for idx, full_wave in saved_full_waves.items():
                local_results[idx]["wave"] = full_wave

        accelerator.wait_for_everyone()
        gathered = gather_object(local_results)

        if accelerator.is_main_process:
            by_idx: dict[int, dict] = {}
            for item in gathered:
                by_idx[int(item["global_idx"])] = item
            sorted_results = [by_idx[key] for key in sorted(by_idx.keys())]

            # use_set_layer=False -> wavs go directly under output_dir/<type-slug>/.
            # This keeps the output flat for single-set TTS calls. Pass the
            # current cfg/steps/duration so meta.jsonl rows match the generation.
            ensure_dir(output_dir)
            _persist_set_outputs(
                set_cfg=set_cfg,
                sorted_results=sorted_results,
                sample_dir=output_dir,
                use_set_layer=False,
                sample_rate=sample_rate,
                duration_seconds=duration_seconds,
                num_inference_steps=num_inference_steps,
                guidance_scale=cfg_value,
                num_log_per_type=0,
            )

            if asr is not None:
                result = score_records(sorted_results, mode=str(args.wer_normalization))
                (output_dir / "wer.jsonl").write_text(
                    "\n".join(
                        json.dumps(rec, ensure_ascii=False) for rec in result["per_record"]
                    )
                    + "\n",
                    encoding="utf-8",
                )
                summary = {
                    "set": set_cfg["name"],
                    "cfg": cfg_value,
                    "ckpt": str(ckpt_dir),
                    "wer_normalization": str(args.wer_normalization),
                    **result["summary"],
                }
                (output_dir / "wer_summary.json").write_text(
                    json.dumps(summary, ensure_ascii=False, indent=2),
                    encoding="utf-8",
                )
                mw = summary.get("mean_wer")
                if mw is not None:
                    print(f"  mean_wer: {float(mw):.4f}")

            print(f"Wrote {len(sorted_results)} sample(s) to {output_dir}")
    finally:
        if asr is not None:
            asr.unload()
        try:
            vae_model.to("cpu")
        except Exception:
            pass
        del transformer_model, scheduler, forward_transformer, vae_model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
